name: Run E2E tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        wordpress: ['6.9', '7.0']
    name: E2E Tests on WordPress ${{ matrix.wordpress }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v4.1.7

      - name: Set up PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
        env:
          fail-fast: 'true'

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
  
      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: lts/*
          cache: npm

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install Playwright dependencies
        timeout-minutes: 10
        run: sudo -E npx playwright install-deps chrome

      - name: Install VIP CLI
        run: npm install -g @automattic/vip

      - name: Create development environment
        run: vip dev-env create --wordpress ${{ matrix.wordpress }} < /dev/null

      - name: Start development environment
        run: vip dev-env start --slug example-integration --skip-wp-versions-check

      - name: Update user password
        run: vip dev-env exec -- wp user update vipgo --user_pass=password

      - name: Run E2E tests
        run: npm test
        env:
          E2E_URL: http://example-integration.vipdev.lndo.site/

      - name: Archive test results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: failure()
        with:
          name: test-results
          path: .playwright
          retention-days: 7
