name: Integration Conformance

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  validate:
    name: Validate integration conformance
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: lts/*

      - name: Run conformance checker
        run: npx --yes @automattic/vip-integration validate
